Deliverable 3: Optimize the model to get over 75% accuracy

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN','NAME'], axis=1)

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Determine which values to replace if counts are less than 500?
replace_application = list(application_type_counts[application_type_counts < 500].index)

# Replace in dataframe
for app in replace_application:
    application_df.APPLICATION_TYPE = application_df.APPLICATION_TYPE.replace(app,"Other")
    
# Check to make sure binning was successful
application_df.APPLICATION_TYPE.value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Determine which values to replace if counts are less than 1800?
replace_class = list(classification_counts[classification_counts < 1800].index)

# Replace in dataframe
for cls in replace_class:
    application_df.CLASSIFICATION = application_df.CLASSIFICATION.replace(cls,"Other")
    
# Check to make sure binning was successful
application_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [6]:
# Generate our categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes=='object'].index.tolist()
application_cat

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_df[application_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(application_cat)
encode_df.head()

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [8]:
# Merge one-hot encoded features and drop the originals
application_df = application_df.merge(encode_df,left_index=True, right_index=True)
application_df = application_df.drop(application_cat,1)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [9]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

Original Model

In [10]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 80)                3520
_________________________________________________________________
dense_1 (Dense)              (None, 30)                2430
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31
=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [11]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=30)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/30
804/804 [==============================] - 1s 620us/step - loss: 0.6031 - accuracy: 0.6924
Epoch 2/30
804/804 [==============================] - 0s 619us/step - loss: 0.5580 - accuracy: 0.7298
Epoch 3/30
804/804 [==============================] - 1s 623us/step - loss: 0.5559 - accuracy: 0.7242
Epoch 4/30
804/804 [==============================] - 1s 650us/step - loss: 0.5474 - accuracy: 0.7359
Epoch 5/30
804/804 [==============================] - 1s 780us/step - loss: 0.5461 - accuracy: 0.7338
Epoch 6/30
804/804 [==============================] - 1s 719us/step - loss: 0.5470 - accuracy: 0.7350
Epoch 7/30
804/804 [==============================] - 1s 636us/step - loss: 0.5485 - accuracy: 0.7329
Epoch 8/30
804/804 [==============================] - 0s 611us/step - loss: 0.5511 - accuracy: 0.7297
Epoch 9/30
804/804 [==============================] - 0s 607us/step - loss: 0.5434 - accuracy: 0.7355
Epoch 10/30
804/804 [==============================] - 0s 617us/step - loss: 0.5431 - accuracy: 0.7386
Epoch 11/30
804/804 [==============================] - 0s 614us/step - loss: 0.5443 - accuracy: 0.7357
Epoch 12/30
804/804 [==============================] - 0s 611us/step - loss: 0.5458 - accuracy: 0.7380
Epoch 13/30
804/804 [==============================] - 1s 636us/step - loss: 0.5422 - accuracy: 0.7375
Epoch 14/30
804/804 [==============================] - 1s 638us/step - loss: 0.5441 - accuracy: 0.7378
Epoch 15/30
804/804 [==============================] - 0s 607us/step - loss: 0.5409 - accuracy: 0.7383
Epoch 16/30
804/804 [==============================] - 0s 606us/step - loss: 0.5483 - accuracy: 0.7316
Epoch 17/30
804/804 [==============================] - 0s 608us/step - loss: 0.5435 - accuracy: 0.7351
Epoch 18/30
804/804 [==============================] - 0s 611us/step - loss: 0.5402 - accuracy: 0.7383
Epoch 19/30
804/804 [==============================] - 0s 613us/step - loss: 0.5389 - accuracy: 0.7432
Epoch 20/30
804/804 [==============================] - 0s 615us/step - loss: 0.5448 - accuracy: 0.7345
Epoch 21/30
804/804 [==============================] - 0s 616us/step - loss: 0.5381 - accuracy: 0.7407
Epoch 22/30
804/804 [==============================] - 0s 619us/step - loss: 0.5422 - accuracy: 0.7342
Epoch 23/30
804/804 [==============================] - 0s 612us/step - loss: 0.5461 - accuracy: 0.7355
Epoch 24/30
804/804 [==============================] - 1s 645us/step - loss: 0.5416 - accuracy: 0.7372
Epoch 25/30
804/804 [==============================] - 0s 603us/step - loss: 0.5428 - accuracy: 0.7343
Epoch 26/30
804/804 [==============================] - 0s 611us/step - loss: 0.5371 - accuracy: 0.7416
Epoch 27/30
804/804 [==============================] - 1s 627us/step - loss: 0.5434 - accuracy: 0.7360
Epoch 28/30
804/804 [==============================] - 1s 713us/step - loss: 0.5430 - accuracy: 0.7347
Epoch 29/30
804/804 [==============================] - 0s 620us/step - loss: 0.5478 - accuracy: 0.7297
Epoch 30/30
804/804 [==============================] - 0s 614us/step - loss: 0.5426 - accuracy: 0.7365
268/268 - 0s - loss: 0.5499 - accuracy: 0.7271
Loss: 0.549929141998291, Accuracy: 0.7271137237548828

Optimzation Attempt 1: Add neurons to hidden layers

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  132
hidden_nodes_layer2 = 66

nn_opt1 = tf.keras.models.Sequential()

# First hidden layer
nn_opt1.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_opt1.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_opt1.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_opt1.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_9 (Dense)              (None, 132)               5808
_________________________________________________________________
dense_10 (Dense)             (None, 66)                8778
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 67
=================================================================
Total params: 14,653
Trainable params: 14,653
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Compile the model
nn_opt1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model_opt1 = nn_opt1.fit(X_train_scaled,y_train,epochs=30)

# Evaluate the model using the test data
model_loss_opt1, model_accuracy_opt1 = nn_opt1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss_opt1}, Accuracy: {model_accuracy_opt1}")

Epoch 1/30
804/804 [==============================] - 1s 689us/step - loss: 0.5821 - accuracy: 0.7127
Epoch 2/30
804/804 [==============================] - 1s 670us/step - loss: 0.5547 - accuracy: 0.7346
Epoch 3/30
804/804 [==============================] - 1s 677us/step - loss: 0.5542 - accuracy: 0.7315
Epoch 4/30
804/804 [==============================] - 1s 688us/step - loss: 0.5502 - accuracy: 0.7322
Epoch 5/30
804/804 [==============================] - 1s 770us/step - loss: 0.5499 - accuracy: 0.7339
Epoch 6/30
804/804 [==============================] - 1s 659us/step - loss: 0.5516 - accuracy: 0.7308
Epoch 7/30
804/804 [==============================] - 1s 661us/step - loss: 0.5490 - accuracy: 0.7325
Epoch 8/30
804/804 [==============================] - 1s 670us/step - loss: 0.5395 - accuracy: 0.7430
Epoch 9/30
804/804 [==============================] - 1s 692us/step - loss: 0.5465 - accuracy: 0.7339
Epoch 10/30
804/804 [==============================] - 1s 672us/step - loss: 0.5465 - accuracy: 0.7347
Epoch 11/30
804/804 [==============================] - 1s 655us/step - loss: 0.5470 - accuracy: 0.7364
Epoch 12/30
804/804 [==============================] - 1s 664us/step - loss: 0.5469 - accuracy: 0.7331
Epoch 13/30
804/804 [==============================] - 1s 666us/step - loss: 0.5452 - accuracy: 0.7354
Epoch 14/30
804/804 [==============================] - 1s 671us/step - loss: 0.5426 - accuracy: 0.7357
Epoch 15/30
804/804 [==============================] - 1s 672us/step - loss: 0.5413 - accuracy: 0.7392
Epoch 16/30
804/804 [==============================] - 1s 727us/step - loss: 0.5437 - accuracy: 0.7361
Epoch 17/30
804/804 [==============================] - 1s 734us/step - loss: 0.5442 - accuracy: 0.7370
Epoch 18/30
804/804 [==============================] - 1s 690us/step - loss: 0.5463 - accuracy: 0.7348
Epoch 19/30
804/804 [==============================] - 1s 711us/step - loss: 0.5389 - accuracy: 0.7395
Epoch 20/30
804/804 [==============================] - 1s 671us/step - loss: 0.5402 - accuracy: 0.7396
Epoch 21/30
804/804 [==============================] - 1s 668us/step - loss: 0.5393 - accuracy: 0.7429
Epoch 22/30
804/804 [==============================] - 1s 703us/step - loss: 0.5470 - accuracy: 0.7329
Epoch 23/30
804/804 [==============================] - 1s 662us/step - loss: 0.5408 - accuracy: 0.7389
Epoch 24/30
804/804 [==============================] - 1s 660us/step - loss: 0.5421 - accuracy: 0.7417
Epoch 25/30
804/804 [==============================] - 1s 666us/step - loss: 0.5420 - accuracy: 0.7383
Epoch 26/30
804/804 [==============================] - 1s 663us/step - loss: 0.5399 - accuracy: 0.7401
Epoch 27/30
804/804 [==============================] - 1s 719us/step - loss: 0.5400 - accuracy: 0.7406
Epoch 28/30
804/804 [==============================] - 1s 668us/step - loss: 0.5460 - accuracy: 0.7350
Epoch 29/30
804/804 [==============================] - 1s 672us/step - loss: 0.5433 - accuracy: 0.7377
Epoch 30/30
804/804 [==============================] - 1s 664us/step - loss: 0.5375 - accuracy: 0.7412
268/268 - 0s - loss: 0.5537 - accuracy: 0.7250
Loss: 0.5537039041519165, Accuracy: 0.7250145673751831

Optimzation Attempt 2: Change Activation Function

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn_opt2 = tf.keras.models.Sequential()

# First hidden layer
nn_opt2.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="tanh")
)

# Second hidden layer
nn_opt2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="tanh"))

# Output layer
nn_opt2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_opt2.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 80)                3520
_________________________________________________________________
dense_13 (Dense)             (None, 30)                2430
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 31
=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn_opt2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model_opt2 = nn_opt2.fit(X_train_scaled,y_train,epochs=30)

# Evaluate the model using the test data
model_loss_opt2, model_accuracy_opt2 = nn_opt2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss_opt2}, Accuracy: {model_accuracy_opt2}")

Epoch 1/30
804/804 [==============================] - 1s 624us/step - loss: 0.5895 - accuracy: 0.7024
Epoch 2/30
804/804 [==============================] - 1s 647us/step - loss: 0.5517 - accuracy: 0.7338
Epoch 3/30
804/804 [==============================] - 0s 611us/step - loss: 0.5527 - accuracy: 0.7343
Epoch 4/30
804/804 [==============================] - 0s 609us/step - loss: 0.5458 - accuracy: 0.7326
Epoch 5/30
804/804 [==============================] - 0s 611us/step - loss: 0.5467 - accuracy: 0.7356
Epoch 6/30
804/804 [==============================] - 0s 621us/step - loss: 0.5504 - accuracy: 0.7313
Epoch 7/30
804/804 [==============================] - 1s 644us/step - loss: 0.5469 - accuracy: 0.7350
Epoch 8/30
804/804 [==============================] - 1s 654us/step - loss: 0.5464 - accuracy: 0.7345
Epoch 9/30
804/804 [==============================] - 0s 603us/step - loss: 0.5488 - accuracy: 0.7311
Epoch 10/30
804/804 [==============================] - 1s 621us/step - loss: 0.5437 - accuracy: 0.7357
Epoch 11/30
804/804 [==============================] - 0s 616us/step - loss: 0.5431 - accuracy: 0.7374
Epoch 12/30
804/804 [==============================] - 1s 631us/step - loss: 0.5471 - accuracy: 0.7352
Epoch 13/30
804/804 [==============================] - 0s 618us/step - loss: 0.5422 - accuracy: 0.7388
Epoch 14/30
804/804 [==============================] - 1s 638us/step - loss: 0.5366 - accuracy: 0.7409
Epoch 15/30
804/804 [==============================] - 1s 678us/step - loss: 0.5469 - accuracy: 0.7348
Epoch 16/30
804/804 [==============================] - 1s 768us/step - loss: 0.5464 - accuracy: 0.7360
Epoch 17/30
804/804 [==============================] - 0s 603us/step - loss: 0.5399 - accuracy: 0.7406
Epoch 18/30
804/804 [==============================] - 0s 605us/step - loss: 0.5404 - accuracy: 0.7340
Epoch 19/30
804/804 [==============================] - 0s 600us/step - loss: 0.5400 - accuracy: 0.7402
Epoch 20/30
804/804 [==============================] - 0s 608us/step - loss: 0.5381 - accuracy: 0.7409
Epoch 21/30
804/804 [==============================] - 1s 658us/step - loss: 0.5352 - accuracy: 0.7421
Epoch 22/30
804/804 [==============================] - 1s 673us/step - loss: 0.5367 - accuracy: 0.7384
Epoch 23/30
804/804 [==============================] - 0s 604us/step - loss: 0.5361 - accuracy: 0.7409
Epoch 24/30
804/804 [==============================] - 1s 638us/step - loss: 0.5436 - accuracy: 0.7381
Epoch 25/30
804/804 [==============================] - 0s 610us/step - loss: 0.5437 - accuracy: 0.7316
Epoch 26/30
804/804 [==============================] - 0s 610us/step - loss: 0.5387 - accuracy: 0.7395
Epoch 27/30
804/804 [==============================] - 0s 606us/step - loss: 0.5409 - accuracy: 0.7381
Epoch 28/30
804/804 [==============================] - 1s 625us/step - loss: 0.5410 - accuracy: 0.7384
Epoch 29/30
804/804 [==============================] - 0s 611us/step - loss: 0.5372 - accuracy: 0.7423
Epoch 30/30
804/804 [==============================] - 0s 605us/step - loss: 0.5386 - accuracy: 0.7410
268/268 - 0s - loss: 0.5510 - accuracy: 0.7252
Loss: 0.5509985089302063, Accuracy: 0.7252478003501892

Optimzation Attempt 3: Add a third and fourth hidden layer

In [19]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 132
hidden_nodes_layer2 = 66
hidden_nodes_layer3 = 33
hidden_nodes_layer4 = 12

nn_opt3 = tf.keras.models.Sequential()

# First hidden layer
nn_opt3.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_opt3.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn_opt3.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Fourth hidden layer
nn_opt3.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))

# Output layer
nn_opt3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_opt3.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_15 (Dense)             (None, 132)               5808
_________________________________________________________________
dense_16 (Dense)             (None, 66)                8778
_________________________________________________________________
dense_17 (Dense)             (None, 33)                2211
_________________________________________________________________
dense_18 (Dense)             (None, 12)                408
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 13
=================================================================
Total params: 17,218
Trainable params: 17,218
Non-trainable params: 0
_________________________________________________________________

In [20]:
# Compile the model
nn_opt3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model_opt3 = nn_opt3.fit(X_train_scaled,y_train,epochs=30)

# Evaluate the model using the test data
model_loss_opt3, model_accuracy_opt3 = nn_opt3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss_opt3}, Accuracy: {model_accuracy_opt3}")

Epoch 1/30
804/804 [==============================] - 1s 754us/step - loss: 0.5973 - accuracy: 0.6993
Epoch 2/30
804/804 [==============================] - 1s 760us/step - loss: 0.5528 - accuracy: 0.7315
Epoch 3/30
804/804 [==============================] - 1s 730us/step - loss: 0.5518 - accuracy: 0.7346
Epoch 4/30
804/804 [==============================] - 1s 782us/step - loss: 0.5538 - accuracy: 0.7275
Epoch 5/30
804/804 [==============================] - 1s 733us/step - loss: 0.5514 - accuracy: 0.7289
Epoch 6/30
804/804 [==============================] - 1s 748us/step - loss: 0.5481 - accuracy: 0.7346
Epoch 7/30
804/804 [==============================] - 1s 782us/step - loss: 0.5431 - accuracy: 0.7361
Epoch 8/30
804/804 [==============================] - 1s 733us/step - loss: 0.5469 - accuracy: 0.7325
Epoch 9/30
804/804 [==============================] - 1s 747us/step - loss: 0.5487 - accuracy: 0.7357
Epoch 10/30
804/804 [==============================] - 1s 752us/step - loss: 0.5484 - accuracy: 0.7347
Epoch 11/30
804/804 [==============================] - 1s 797us/step - loss: 0.5419 - accuracy: 0.7374
Epoch 12/30
804/804 [==============================] - 1s 806us/step - loss: 0.5397 - accuracy: 0.7395
Epoch 13/30
804/804 [==============================] - 1s 735us/step - loss: 0.5441 - accuracy: 0.7366
Epoch 14/30
804/804 [==============================] - 1s 719us/step - loss: 0.5410 - accuracy: 0.7404
Epoch 15/30
804/804 [==============================] - 1s 864us/step - loss: 0.5435 - accuracy: 0.7393
Epoch 16/30
804/804 [==============================] - 1s 740us/step - loss: 0.5455 - accuracy: 0.7358
Epoch 17/30
804/804 [==============================] - 1s 751us/step - loss: 0.5432 - accuracy: 0.7410
Epoch 18/30
804/804 [==============================] - 1s 735us/step - loss: 0.5421 - accuracy: 0.7387
Epoch 19/30
804/804 [==============================] - 1s 736us/step - loss: 0.5438 - accuracy: 0.7362
Epoch 20/30
804/804 [==============================] - 1s 794us/step - loss: 0.5403 - accuracy: 0.7396
Epoch 21/30
804/804 [==============================] - 1s 735us/step - loss: 0.5397 - accuracy: 0.7410
Epoch 22/30
804/804 [==============================] - 1s 731us/step - loss: 0.5386 - accuracy: 0.7425
Epoch 23/30
804/804 [==============================] - 1s 746us/step - loss: 0.5359 - accuracy: 0.7434
Epoch 24/30
804/804 [==============================] - 1s 731us/step - loss: 0.5471 - accuracy: 0.7344
Epoch 25/30
804/804 [==============================] - 1s 776us/step - loss: 0.5395 - accuracy: 0.7395
Epoch 26/30
804/804 [==============================] - 1s 732us/step - loss: 0.5372 - accuracy: 0.7410
Epoch 27/30
804/804 [==============================] - 1s 792us/step - loss: 0.5391 - accuracy: 0.7395
Epoch 28/30
804/804 [==============================] - 1s 742us/step - loss: 0.5373 - accuracy: 0.7410
Epoch 29/30
804/804 [==============================] - 1s 765us/step - loss: 0.5381 - accuracy: 0.7403
Epoch 30/30
804/804 [==============================] - 1s 749us/step - loss: 0.5438 - accuracy: 0.7342
268/268 - 0s - loss: 0.5525 - accuracy: 0.7268
Loss: 0.5525211691856384, Accuracy: 0.7267638444900513

In [21]:
print(f"Original Model - Loss: {model_loss:,.4f}, Accuracy: {model_accuracy:,.4f}")
print(f"Optimization 1 - Loss: {model_loss_opt1:,.4f}, Accuracy: {model_accuracy_opt1:,.4f}")
print(f"Optimization 2 - Loss: {model_loss_opt2:,.4f}, Accuracy: {model_accuracy_opt2:,.4f}")
print(f"Optimization 3 - Loss: {model_loss_opt3:,.4f}, Accuracy: {model_accuracy_opt3:,.4f}")

Original Model - Loss: 0.5499, Accuracy: 0.7271
Optimization 1 - Loss: 0.5537, Accuracy: 0.7250
Optimization 2 - Loss: 0.5510, Accuracy: 0.7252
Optimization 3 - Loss: 0.5525, Accuracy: 0.7268

In [22]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimzation.h5")